recipe refactoring  - static binaries build with musl  - busibox from 'busybox:uclibc'  - openvpn version upgraded (2.4.9)  - licenses added  - binaries strip  - global args (dockerfile)  - 'run' script renamed to 'entrypoint'  - entrypoint script allows running other commands  - mozilla root certificates  - documentation updated

diff --git a/files/scripts/ovpn_delclient b/files/scripts/ovpn_delclient
--- a/files/scripts/ovpn_delclient
+++ b/files/scripts/ovpn_delclient
@@ -19,8 +19,8 @@ BASENAME=$(basename "${0}")
 OPENVPN_USERNAME=
 
 __EASYRSA_DIR__="/usr/local/easyrsa"
-__EASYRSA_DATA__="/data/easyrsa"
-__OPENVPN_DATA__="/data/openvpn"
+__EASYRSA_DATA__="${EASYRSA_DATA_DIR:-/data/easyrsa}"
+__OPENVPN_DATA__="${OPENVPN_DATA_DIR:-/data/openvpn}"
 
 # Configuration files
 EASYRSA_VARS="${__EASYRSA_DIR__}/vars"
@@ -63,7 +63,7 @@ fi
 
 # Check if client credentials exist
 if [ ! -f "${__EASYRSA_DATA__}/pki/private/${OPENVPN_USERNAME}.key" ]; then
-  echo >&2 "  [ERROR] Unable to find client ${OPENVPN_USERNAME} information."
+  echo >&2 "  [ERROR] Unable to find client '${OPENVPN_USERNAME}' information."
   exit 5
 fi
 
diff --git a/files/scripts/ovpn_getclient b/files/scripts/ovpn_getclient
--- a/files/scripts/ovpn_getclient
+++ b/files/scripts/ovpn_getclient
@@ -18,8 +18,8 @@ BASENAME=$(basename "${0}")
 # Variables
 OPENVPN_USERNAME=
 
-__EASYRSA_DATA__="/data/easyrsa"
-__OPENVPN_DATA__="/data/openvpn"
+__EASYRSA_DATA__="${EASYRSA_DATA_DIR:-/data/easyrsa}"
+__OPENVPN_DATA__="${OPENVPN_DATA_DIR:-/data/openvpn}"
 
 # Configuration files
 OPENVPN_ENV="${__OPENVPN_DATA__}/env"
@@ -62,7 +62,7 @@ fi
 
 # Check if client credentials exist
 if [ ! -f "${__EASYRSA_DATA__}/pki/private/${OPENVPN_USERNAME}.key" ]; then
-  echo >&2 "  [ERROR] Unable to find client ${OPENVPN_USERNAME} information."
+  echo >&2 "  [ERROR] Unable to find client '${OPENVPN_USERNAME}' information."
   exit 5
 fi
 
@@ -78,9 +78,11 @@ fi
 cat <<EOF
 client
 nobind
+proto ${OVPN_SERVER_PROTO}
 dev tun
 resolv-retry infinite
 remote-cert-tls server
+tls-client
 <key>
 $(cat "${__EASYRSA_DATA__}/pki/private/${OPENVPN_USERNAME}.key")
 </key>
@@ -93,9 +95,13 @@ $(cat "${__EASYRSA_DATA__}/pki/ca.crt")
 <tls-auth>
 $(cat "${__EASYRSA_DATA__}/pki/ta.key")
 </tls-auth>
+pull
 comp-lzo
 key-direction 1
 remote ${OVPN_SERVER_CN} ${OVPN_SERVER_PORT} ${OVPN_SERVER_PROTO}
+persist-key
+persist-tun
+verb 3
 EOF
 [ "${OVPN_DEFROUTE}" -gt 0 ] && echo 'redirect-gateway def1'
 
diff --git a/files/tests/in_sanity b/files/tests/in_sanity
--- a/files/tests/in_sanity
+++ b/files/tests/in_sanity
@@ -29,7 +29,7 @@ else
   exit 2
 fi
 
-printf '[TEST] Check if Root Certificates are installed... '
+printf '[TEST] Check if OpenSSL (and Root Certificates) can be used... '
 if (echo | openssl s_client -connect google.com:443 2>&1) | grep -q 'Verify return code: 0 (ok)'; then
   echo 'OK'
 else
@@ -51,6 +51,22 @@ if easyrsa help > /dev/null 2>&1; then
 else
   echo 'Failed'
   exit 5
+fi
+
+printf '[TEST] Check if Busybox is installed... '
+if busybox > /dev/null 2>&1; then
+  echo 'OK'
+else
+  echo 'Failed'
+  exit 6
+fi
+
+printf '[TEST] Check OpenVPN crypto capabilities... '
+if (openvpn --genkey --secret test.key && openvpn --cipher aes-128-cbc --test-crypto --secret test.key && openvpn --cipher aes-256-cbc --test-crypto --secret test.key && openvpn --cipher aes-128-gcm --test-crypto --secret test.key && openvpn --cipher aes-256-gcm --test-crypto --secret test.key) > /dev/null 2>&1; then
+  echo 'OK'
+else
+  echo 'Failed'
+  exit 7
 fi
 
 exit 0
