scripts moved

diff --git a/files/scripts/run b/files/scripts/run
--- a/files/scripts/run
+++ b/files/scripts/run
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # Shell script to start the OpenVPN Docker image.
 #
@@ -26,22 +26,28 @@ CERTIFICATE_CN=
 OVPN_CLIENT_TO_CLIENT=0
 OVPN_DEFROUTE=1
 OVPN_DNS=1
-OVPN_NS=()
-OVPN_PUSH=()
-OVPN_ROUTES=()
+#OVPN_NS=()
+#OVPN_PUSH=()
+#OVPN_ROUTES=()
+OVPN_NS=""
+OVPN_PUSH=""
+OVPN_ROUTES=""
 OVPN_SERVER_ADDR=
 OVPN_SERVER_CN=
 OVPN_SERVER_PORT=
 OVPN_SERVER_PROTO=
 OVPN_SERVER_CIDR="172.16.61.0/24"
 
-__EASYRSA_DIR__="/opt/easyrsa"
+__EASYRSA_DIR__="/usr/local/easyrsa"
 __EASYRSA_DATA__="/data/easyrsa"
 __OPENVPN_DATA__="/data/openvpn"
 
-__TMP_NS__=()
-__TMP_PUSH__=()
-__TMP_ROUTES__=()
+#__TMP_NS__=()
+#__TMP_PUSH__=()
+#__TMP_ROUTES__=()
+__TMP_NS__=""
+__TMP_PUSH__=""
+__TMP_ROUTES__=""
 
 
 # Configuration files
@@ -52,7 +58,7 @@ OPENVPN_STATUS="${__OPENVPN_DATA__}/openvpn.status"
 
 
 # Usage
-function show_usage() {
+show_usage() {
   echo "Usage: ${BASENAME} [options] (help|init|start)"
   echo "  help:"
   echo "    <none>"
@@ -75,8 +81,8 @@ function show_usage() {
 
 # Convert CIDR to Netmask
 cidr_to_mask() {
-  set -- $(( 5 - ($1 / 8) )) 255 255 255 255 $(( (255 << (8 - ($1 % 8))) & 255 )) 0 0 0
-  [[ "${1}" -gt 1 ]] && shift "${1}" || shift
+  set -- $(( 5 - (${1} / 8) )) 255 255 255 255 $(( (255 << (8 - (${1} % 8))) & 255 )) 0 0 0
+  [ "${1}" -gt 1 ] && shift "${1}" || shift
   echo "${1-0}.${2-0}.${3-0}.${4-0}"
 }
 
@@ -88,13 +94,13 @@ get_route() {
 
 
 # Import env
-if [[ -f ${OPENVPN_ENV} ]]; then
+if [ -f ${OPENVPN_ENV} ]; then
   . ${OPENVPN_ENV}
 fi
 
 
 # Options parsing
-while getopts ":c:Cdgn:Np:r:s:u:" opt; do
+while getopts ":c:Cdgn:p:r:s:u:" opt; do
   case ${opt} in
     c)
       CERTIFICATE_CN=${OPTARG}
@@ -109,13 +115,16 @@ while getopts ":c:Cdgn:Np:r:s:u:" opt; do
       OVPN_DEFROUTE=0
       ;;
     n)
-      __TMP_NS__+=("${OPTARG}")
+      #__TMP_NS__+=("${OPTARG}")
+      __TMP_NS__="${__TMP_NS__} ${OPTARG}"
       ;;
     p)
-      __TMP_PUSH__+=("${OPTARG}")
+      #__TMP_PUSH__+=("${OPTARG}")
+      __TMP_PUSH__="${__TMP_PUSH__} $(echo "${OPTARG}" | tr ' ' '_')"
       ;;
     r)
-      __TMP_ROUTES__+=("${OPTARG}")
+      #__TMP_ROUTES__+=("${OPTARG}")
+      __TMP_ROUTES__="${__TMP_ROUTES__} ${OPTARG}"
       ;;
     s)
       OVPN_SERVER_CIDR=${OPTARG}
@@ -137,14 +146,14 @@ done
 shift $((OPTIND-1))
 
 for command in "${@}"; do
-  case "${command,,}" in
-    help)
+  case "${command}" in
+    [Hh][Ee][Ll][Pp])
       ACTION_HELP=1
       ;;
-    init)
+    [Ii][Nn][Ii][Tt])
       ACTION_INIT=1
       ;;
-    start)
+    [Ss][Tt][Aa][Rr][Tt])
       ACTION_START=1
       ;;
     *)
@@ -155,55 +164,71 @@ done
 
 
 # Check arguments
-if [[ $# -eq 0 ]]; then
+if [ $# -eq 0 ]; then
   show_usage
   exit 3
 fi
-if ! ((ACTION_HELP+ACTION_INIT+ACTION_START)); then
+if [ "$((ACTION_HELP+ACTION_INIT+ACTION_START))" -eq 0 ]; then
   show_usage
   exit 0
 fi
 
 
 # Check permissions
-if [[ $EUID -ne 0 ]]; then
+if [ "$(id -u)" -ne 0 ]; then
   echo >&2 "  [ERROR] This script requires privileged access to system files"
   exit 4
 fi
 
 
 # === HELP ===
-if [[ "${ACTION_HELP}" -gt 0 ]]; then
+if [ "${ACTION_HELP}" -gt 0 ]; then
   show_usage
   exit 0
 fi
 
 
 # === INIT ===
-if [[ "${ACTION_INIT}" -gt 0 ]]; then
+if [ "${ACTION_INIT}" -gt 0 ]; then
 
   # Check requirements
-  if [[ "x${CERTIFICATE_CN}" = "x" ]]; then
+  if [ "x${CERTIFICATE_CN}" = "x" ]; then
     echo >&2 "  [ERROR] The Common Name (-c) option is mandatory."
     exit 5
   fi
-  if [[ "x${OVPN_SERVER_ADDR}" = "x" ]]; then
+  if [ "x${OVPN_SERVER_ADDR}" = "x" ]; then
     echo >&2 "  [ERROR] The OpenVPN public DNS name (-u) option is required."
     exit 6
   fi
-  if [[ "x${OVPN_SERVER_CIDR}" = "x" ]]; then
+  if [ "x${OVPN_SERVER_CIDR}" = "x" ]; then
     echo >&2 "  [ERROR] The OpenVPN subnet (-s) option is required."
     exit 7
   fi
-  if ! [[ "${OVPN_SERVER_CIDR}" =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$ ]]; then
+  #if ! [[ "${OVPN_SERVER_CIDR}" =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$ ]]; then
+  #  echo >&2 "  [ERROR] The OpenVPN subnet (-s) option has an invalid format."
+  #  exit 8
+  #fi
+  eval $(echo "${OVPN_SERVER_CIDR}" | sed -n -r -e "s,^((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2])))$,VALID_SERVER_CIDR='\1',p")
+  if [ -z "${VALID_SERVER_CIDR}" ]; then
     echo >&2 "  [ERROR] The OpenVPN subnet (-s) option has an invalid format."
     exit 8
+  fi
+
+  # Create configuration dir(s)
+  if ! [ -d "${__EASYRSA_DATA__}" ]; then
+    mkdir -p ${__EASYRSA_DATA__}
+    chmod 0755 ${__EASYRSA_DATA__}
+  fi
+  if ! [ -d "${__OPENVPN_DATA__}" ]; then
+    mkdir -p ${__OPENVPN_DATA__}
+    chmod 0755 ${__OPENVPN_DATA__}
   fi
 
   ## --- init ---
 
   # Copy required files to EasyRSA
-  cp -r ${__EASYRSA_DIR__}/{x509-types,openssl-1.0.cnf} ${__EASYRSA_DATA__}/
+  cp -r ${__EASYRSA_DIR__}/x509-types ${__EASYRSA_DATA__}/
+  cp ${__EASYRSA_DIR__}/openssl-easyrsa.cnf ${__EASYRSA_DATA__}/
 
   # Initialize (clean up) the CA PKI directory
   easyrsa --vars=${EASYRSA_VARS} --batch init-pki
@@ -221,7 +246,11 @@ if [[ "${ACTION_INIT}" -gt 0 ]]; then
   easyrsa --vars=${EASYRSA_VARS} gen-crl
 
   # Copy required files to OpenVPN
-  cp ${__EASYRSA_DATA__}/pki/{ta.key,ca.crt,crl.pem,issued/server.crt,private/server.key} ${__OPENVPN_DATA__}/
+  cp ${__EASYRSA_DATA__}/pki/ta.key ${__OPENVPN_DATA__}/
+  cp ${__EASYRSA_DATA__}/pki/ca.crt ${__OPENVPN_DATA__}/
+  cp ${__EASYRSA_DATA__}/pki/crl.pem ${__OPENVPN_DATA__}/
+  cp ${__EASYRSA_DATA__}/pki/issued/server.crt ${__OPENVPN_DATA__}/
+  cp ${__EASYRSA_DATA__}/pki/private/server.key ${__OPENVPN_DATA__}/
 
   ## --- config ---
 
@@ -229,39 +258,52 @@ if [[ "${ACTION_INIT}" -gt 0 ]]; then
   openssl dhparam -out ${__OPENVPN_DATA__}/dh2048.pem 2048 && \
 
   # Backup configuration files
-  if [[ -f ${OPENVPN_CONF} ]]; then
+  if [ -f ${OPENVPN_CONF} ]; then
     cp "${OPENVPN_CONF}" "${OPENVPN_CONF}.${__TS__}.bck"
   fi
-  if [[ -f ${OPENVPN_ENV} ]]; then
+  if [ -f ${OPENVPN_ENV} ]; then
     cp "${OPENVPN_ENV}" "${OPENVPN_ENV}.${__TS__}.bck"
   fi
 
   # Set client routes
-  #OVPN_ROUTES=($(tr ' ' '\n' <<< "${__TMP_ROUTES__[@]} ${OVPN_SERVER_CIDR}" | sort -u | tr '\n' ' '))
-  OVPN_ROUTES=($(tr ' ' '\n' <<< "${__TMP_ROUTES__[@]}" | sort -u | tr '\n' ' '))
+  #OVPN_ROUTES=($(tr ' ' '\n' <<< "${__TMP_ROUTES__[@]}" | sort -u | tr '\n' ' '))
+  OVPN_ROUTES=$(echo "${__TMP_ROUTES__}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
 
   # Set client rules
-  OVPN_PUSH=($(tr ' ' '\n' <<< "${__TMP_PUSH__[@]// /_}" | sort -u | tr '\n' ' '))
+  #OVPN_PUSH=($(tr ' ' '\n' <<< "${__TMP_PUSH__[@]// /_}" | sort -u | tr '\n' ' '))
+  OVPN_PUSH=$(echo "${__TMP_PUSH__}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
 
   # Set nameservers
-  if [[ ${#__TMP_NS__[@]} -gt 0 ]]; then
-    OVPN_NS=($(tr ' ' '\n' <<< "${__TMP_NS__[@]}" | sort -u | tr '\n' ' '))
+  #if [ ${#__TMP_NS__[@]} -gt 0 ]; then
+  #  OVPN_NS=($(tr ' ' '\n' <<< "${__TMP_NS__[@]}" | sort -u | tr '\n' ' '))
+  #else
+  #  OVPN_NS=("8.8.8.8" "8.8.4.4")
+  #fi
+  if [ -z "${__TMP_NS__}" ]; then
+    OVPN_NS="8.8.8.8 8.8.4.4"
   else
-    OVPN_NS=("8.8.8.8" "8.8.4.4")
+    OVPN_NS=$(echo "${__TMP_NS__}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
   fi
 
   # Set the OpenVPN server address
-  if [[ "${OVPN_SERVER_ADDR}" =~ ^((udp|tcp)://)?([0-9a-zA-Z\.\-]+)(:([0-9]+))?$  ]]; then
-    OVPN_SERVER_PROTO=${BASH_REMATCH[2]}
-    OVPN_SERVER_CN=${BASH_REMATCH[3]}
-    OVPN_SERVER_PORT=${BASH_REMATCH[5]}
-  else
+  #if [ "${OVPN_SERVER_ADDR}" =~ ^((udp|tcp)://)?([0-9a-zA-Z\.\-]+)(:([0-9]+))?$ ]; then
+  #  OVPN_SERVER_PROTO=${BASH_REMATCH[2]}
+  #  OVPN_SERVER_CN=${BASH_REMATCH[3]}
+  #  OVPN_SERVER_PORT=${BASH_REMATCH[5]}
+  #else
+  #  echo >&2 "  [ERROR] Invalid OpenVPN public DNS name."
+  #  exit 9
+  #fi
+  #[ -z "${OVPN_SERVER_PROTO}" ] && OVPN_SERVER_PROTO="udp"
+  #[ -z "${OVPN_SERVER_PORT}" ] && OVPN_SERVER_PORT="1194"
+  #OVPN_SERVER_ADDR="${OVPN_SERVER_PROTO}://${OVPN_SERVER_CN}:${OVPN_SERVER_PORT}"
+  eval $(echo "${OVPN_SERVER_ADDR}" | sed -n -r -e "s,^((udp|tcp)://)?([0-9a-zA-Z\.\-]+)(:([0-9]+))?$,OVPN_SERVER_PROTO='\2' OVPN_SERVER_CN='\3' OVPN_SERVER_PORT='\5',p")
+  if [ -z "${OVPN_SERVER_CN}" ]; then
     echo >&2 "  [ERROR] Invalid OpenVPN public DNS name."
     exit 9
+  else
+    OVPN_SERVER_ADDR="${OVPN_SERVER_PROTO:-udp}://${OVPN_SERVER_CN}:${OVPN_SERVER_PORT:-1194}"
   fi
-  [[ -z "${OVPN_SERVER_PROTO}" ]] && OVPN_SERVER_PROTO="udp"
-  [[ -z "${OVPN_SERVER_PORT}" ]] && OVPN_SERVER_PORT="1194"
-  OVPN_SERVER_ADDR="${OVPN_SERVER_PROTO}://${OVPN_SERVER_CN}:${OVPN_SERVER_PORT}"
 
   # Store the values on the env file
   set | grep "^OVPN_" | sort > "${OPENVPN_ENV}"
@@ -288,23 +330,27 @@ persist-tun
 status openvpn.status
 verb 3
 EOF
-  [[ "${OVPN_DEFROUTE}" -gt 0 ]] && echo 'push "redirect-gateway def1 bypass-dhcp"' >> ${OPENVPN_CONF}
-  [[ "${OVPN_CLIENT_TO_CLIENT}" -gt 0 ]] && echo 'client-to-client' >> ${OPENVPN_CONF}
-  if [[ "${OVPN_DNS}" -gt 0 ]]; then
-    for dns in "${OVPN_NS[@]}"; do
+  [ "${OVPN_DEFROUTE}" -gt 0 ] && echo 'push "redirect-gateway def1 bypass-dhcp"' >> ${OPENVPN_CONF}
+  [ "${OVPN_CLIENT_TO_CLIENT}" -gt 0 ] && echo 'client-to-client' >> ${OPENVPN_CONF}
+  if [ "${OVPN_DNS}" -gt 0 ]; then
+    #for dns in "${OVPN_NS[@]}"; do
+    for dns in ${OVPN_NS}; do
       echo "push \"dhcp-option DNS ${dns}\"" >> ${OPENVPN_CONF}
     done
   fi
-  for route in "${OVPN_ROUTES[@]}"; do
+  #for route in "${OVPN_ROUTES[@]}"; do
+  for route in ${OVPN_ROUTES}; do
     echo "route $(get_route "${route}")" >> ${OPENVPN_CONF}
   done
-  for push in "${OVPN_PUSH[@]}"; do
-    echo "push \"${push//_/ }\"" >> ${OPENVPN_CONF}
+  #for push in "${OVPN_PUSH[@]}"; do
+  for push in ${OVPN_PUSH}; do
+    #echo "push \"${push//_/ }\"" >> ${OPENVPN_CONF}
+    echo "push \"$(echo "${push}" | tr '_' ' ')\"" >> ${OPENVPN_CONF}
   done
 
   # Clean up unneeded backups
-  diff -q "${OPENVPN_ENV}" "${OPENVPN_ENV}.${__TS__}.bck" &> /dev/null && rm -f "${OPENVPN_ENV}.${__TS__}.bck" || true
-  diff -q "${OPENVPN_CONF}" "${OPENVPN_CONF}.${__TS__}.bck" &> /dev/null && rm -f "${OPENVPN_CONF}.${__TS__}.bck" || true
+  (diff -q "${OPENVPN_ENV}" "${OPENVPN_ENV}.${__TS__}.bck" > /dev/null 2>&1 && rm -f "${OPENVPN_ENV}.${__TS__}.bck") || true
+  (diff -q "${OPENVPN_CONF}" "${OPENVPN_CONF}.${__TS__}.bck" > /dev/null 2>&1 && rm -f "${OPENVPN_CONF}.${__TS__}.bck") || true
 
   # All done
   echo "  [INFO] Configuration(s) successfully updated"
@@ -312,24 +358,25 @@ fi
 
 
 # === START ===
-if [[ "${ACTION_START}" -gt 0 ]]; then
+if [ "${ACTION_START}" -gt 0 ]; then
 
   # Create temporary dir (if needed)
-  if ! [[ -d /tmp ]]; then
-    mkdir -p -m 1777 /tmp
+  if ! [ -d /tmp ]; then
+    mkdir -m 1777 /tmp
   fi
 
   # Create required device(s)
-  if ! [[ -d /dev/net ]]; then
-    mkdir -p -m 755 /dev/net
+  if ! [ -d /dev/net ]; then
+    mkdir -p /dev/net
+    chmod 0755 /dev /dev/net
   fi
-  if ! [[ -c /dev/net/tun ]]; then
+  if ! [ -c /dev/net/tun ]; then
     mknod /dev/net/tun c 10 200
   fi
 
   # Start the OpenVPN server
-  if [[ -f "${OPENVPN_CONF}" ]]; then
-    /usr/sbin/openvpn --cd ${__OPENVPN_DATA__} --status ${OPENVPN_STATUS} --config ${OPENVPN_CONF}
+  if [ -f "${OPENVPN_CONF}" ]; then
+    openvpn --cd ${__OPENVPN_DATA__} --status ${OPENVPN_STATUS} --config ${OPENVPN_CONF}
   else
     echo >&2 "  [ERROR] OpenVPN configuration not found."
     exit 10
